export const RELATIONSHIP_TYPES = {
  COMMIT_MODIFIED_FILE: 'COMMIT_MODIFIED_FILE',
  FILE_CO_CHANGED: 'FILE_CO_CHANGED',
  PR_CONTAINS_COMMIT: 'PR_CONTAINS_COMMIT',
  DEVELOPER_MODIFIED_FILE: 'DEVELOPER_MODIFIED_FILE',
  ISSUE_REFERENCES_PR: 'ISSUE_REFERENCES_PR',
  MODULE_CONNECTED_TO_MODULE: 'MODULE_CONNECTED_TO_MODULE',
} as const;

export type RelationshipTypeValue =
  (typeof RELATIONSHIP_TYPES)[keyof typeof RELATIONSHIP_TYPES];
